using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SoD2_Editor
{
    public partial class Form1
    {
        public enum EAnalyticsCauseOfDamage : byte
        {
            ACOD_Unknown = 0,
            ACOD_ZombieMeleeAttack = 1,
            ACOD_ZombieBite = 2,
            ACOD_BloaterGas = 3,
            ACOD_HumanMeleeAttack = 4,
            ACOD_HumanGunshot = 5,
            ACOD_Bumped = 6,
            ACOD_BurstEffect = 7,
            ACOD_Fire = 8,
            ACOD_JuggernautAttack = 9,
            ACOD_Vehicle = 10,
            ACOD_VehicleDoor = 11,
            ACOD_FeralAttack = 12,
            ACOD_Environment = 13,
            ACOD_HumanFiredProjectile = 14,
            ACOD_HavenProtocol = 15,
            ACOD_Plague = 16,
            ACOD_MAX = 17
        }
        public enum ECharacterHitType : byte
        {
            Melee = 0,
            Ranged = 1,
            Bumped = 2,
            BurstEffect = 3,
            VehicleExplosion = 4,
            RangedProjectile = 5,
            DirectHealthLoss = 6,
            ECharacterHitType_MAX = 7
        };
        public enum ECharacterPhilosophy : byte
        {
            Daring = 0,
            Prudent = 1,
            Pragmatic = 2,
            Compassionate = 3,
            PhilosophyCount = 4,
            ECharacterPhilosophy_MAX = 5
        }
        public enum ECharacterStanding : byte
        {
            Stranger = 0,
            Recruit = 1,
            Citizen = 2,
            Hero = 3,
            Leader = 4,
            Count = 5,
            ECharacterStanding_MAX = 6
        }
        public enum ECharacterStatType
        {
            NA = 0,
            FoodConsumedPerDayPercentage = 1,
            StaminaMax = 2,
            StaminaMaxModifier = 3,
            StaminaRecoveryModifier = 4,
            HealthMax = 5,
            HealthMaxModifier = 6,
            Trauma = 7,
            TraumaRecoveryRateModifier = 8,
            TraumaSeverityModifier = 9,
            Fatigue = 10,
            FatigueRate = 11,
            FatigueRecoveryRateModifier = 12,
            FatigueSeverityModifier = 13,
            InjuryChanceModifier = 14,
            InjuryRecoveryRateModifier = 15,
            SicknessRecoveryRate = 16,
            SicknessRecoveryRateModifier = 17,
            SicknessChanceModifier = 18,
            SicknessMax = 19,
            BloodPlagueRate = 20,
            BloodPlagueRateModifier = 21,
            BloodPlagueMax = 22,
            FrustrationRateModifier = 23,
            FrustrationRecoveryRateModifier = 24,
            ExperienceRateModifierCardio = 25,
            ExperienceRateModifierWits = 26,
            ExperienceRateModifierFighting = 27,
            ExperienceRateModifierShooting = 28,
            ExperienceRateModifierMechanics = 29,
            ExperienceRateModifierMedicine = 30,
            ExperienceRateModifierCraftsmanship = 31,
            ExperienceRateModifierGardening = 32,
            ExperienceRateModifierCooking = 33,
            ExperienceRateModifierUtilities = 34,
            ExperienceRateModifierChemistry = 35,
            ExperienceRateModifierComputers = 36,
            VehicleFuelEfficiencyModifier = 37,
            VehicleImpactReductionModifier = 38,
            VehicleLoudnessReductionModifier = 39,
            VehicleRefuelEfficiencyModifier = 40,
            VehicleRepairEfficiencyModifier = 41,
            CarryWeightHeavyAdjustment = 42,
            CarryWeightLightAdjustment = 43,
            SearchSpeed = 44,
            ChanceOfCrashModifier = 45,
            SearchSilent = 46,
            Shooting = 47,
            Sharpshooting = 48,
            SharpshootingPerk1 = 49,
            SharpshootingPerk2 = 50,
            Assault = 51,
            AssaultPerk1 = 52,
            AssaultPerk2 = 53,
            Gunslinging = 54,
            GunslingingPerk1 = 55,
            GunslingingPerk2 = 56,
            Hunting = 57,
            HuntingPerk1 = 58,
            HuntingPerk2 = 59,
            DodgeCostModifier = 60,
            GrappleCostModifier = 61,
            FinisherCostModifier = 62,
            MeleeCostModifier = 63,
            SprintCostModifier = 64,
            TraversalCostModifier = 65,
            RangedWeaponBuff0 = 66,
            RangedWeaponBuff1 = 67,
            RangedWeaponBuff2 = 68,
            RangedWeaponBuff3 = 69,
            RangedWeaponBuff4 = 70,
            RangedWeaponBuff5 = 71,
            RangedWeaponBuff6 = 72,
            RangedWeaponBuff7 = 73,
            RangedWeaponBuff8 = 74,
            RangedWeaponBuff9 = 75,
            EnemySightRangeModifier = 76,
            EnemyShootHitChanceModifier = 77,
            ScoutingRangeModifier = 78,
            ScoutingPerk1 = 79,
            ScoutingPerk2 = 80,
            SurveyRange = 81,
            Fighting = 82,
            Endurance = 83,
            EndurancePerk1 = 84,
            EndurancePerk2 = 85,
            Striking = 86,
            StrikingPerk1 = 87,
            StrikingPerk2 = 88,
            Swordplay = 89,
            SwordplayPerk1 = 90,
            SwordplayPerk2 = 91,
            CloseCombat = 92,
            CloseCombatPerk1 = 93,
            CloseCombatPerk2 = 94,
            MeleeWeaponBuff0 = 95,
            MeleeWeaponBuff1 = 96,
            MeleeWeaponBuff2 = 97,
            MeleeWeaponBuff3 = 98,
            MeleeWeaponBuff4 = 99,
            MeleeWeaponBuff5 = 100,
            MeleeWeaponBuff6 = 101,
            MeleeWeaponBuff7 = 102,
            MeleeWeaponBuff8 = 103,
            MeleeWeaponBuff9 = 104,
            RangedWeaponDurabilityModifier = 105,
            MeleeWeaponDurabilityModifier = 106,
            AllWeaponDurabilityModifier = 107,
            ExperienceRateModifierAll = 108,
            PassiveEnemyDetectionRange = 109,
            AggressiveEnemyDetectionRange = 110,
            InventoryCapacity = 111,
            InventoryConsumableMaxStackIncrease = 112,
            InventoryConsumableWeightModifier = 113,
            StandingRateModifier = 114,
            WitsDisciplineStaminaGainOnMeleeKill = 115,
            ContainerShinyVisibilityDistanceModifier = 116,
            CharacterMorale = 117,
            AcrobaticsPerk1 = 118,
            AcrobaticsPerk2 = 119,
            BackpackingPerk1 = 120,
            BackpackingPerk2 = 121,
            MarathonPerk1 = 122,
            MarathonPerk2 = 123,
            PowerhousePerk1 = 124,
            PowerhousePerk2 = 125,
            DisciplinePerk1 = 126,
            DisciplinePerk2 = 127,
            ResourcefulPerk1 = 128,
            ResourcefulPerk2 = 129,
            StealthPerk1 = 130,
            StealthPerk2 = 131,
            NightVision = 132,
            CrossbowBoltRecoverModifierHead = 133,
            CrossbowBoltRecoverModifierBody = 134,
            CrossbowBoltRecoverModifierEnv = 135,
            PlagueSampleDropRateModifier = 136,
            ConsumableHealthGainModifier = 137,
            ConsumableStaminaGainModifier = 138,
            ZombieVisibilityReductionModifier = 139,
            LocomotionNoiseReductionModifier = 140,
            GlobalDamageMultiplier = 141,
            GunNoiseLoudnessModifier = 142,
            SicknessFromAttacksMultiplier = 143,
            SicknessFromConsumablesMultiplier = 144,
            BloodPlagueFromAttacksMultiplier = 145,
            BloodPlagueFromConsumablesMultiplier = 146,
            SicknessFromAttacksInPlagueSphereMultiplier = 147,
            BloodPlagueFromAttacksInPlagueSphereMultiplier = 148,
            JuggernautBonusPlagueSamples = 149,
            InventoryAdditionalAmmoMaxStackPercentage = 150,
            ZombieFireVulnerabilityModifier = 151,
            ZombieHearingRangeModifier = 152,
            ZombieDamageModifier = 153,
            ZombieToughnessModifier = 154,
            ZombieExplode = 155,
            ZombieSurviveHeadless = 156,
            ZombieHoming = 157,
            ZombieVariant = 158,
            ZombieGlow = 159,
            ZombieColor = 160,
            ZombieSightRangeModifier = 161,
            ZombieSightPieAngleModifier = 162,
            ZombieXRayVision = 163,
            ZombieSeekerWanderRadius = 164,
            ZombieSeekerMovementSpeed = 165,
            ZombieFollowTimer = 166,
            ZombieSneakPerceptionModifier = 167,
            ZombieStinky = 168,
            ZombieStinkyStaminaLossPerTick = 169,
            ZombieStinkyHitFrequency = 170,
            ZombieHeadshotCount = 171,
            ZombieDeathLure = 172,
            DropLoot = 173,
            ZombieVehicleImpactDamageModifier = 174,
            ZombiePlagueSampleDropRateModifier = 175,
            ZombieParticles = 176,
            PlagueNodeDisableWaveSpawning = 177,
            HealthItemEffectivenessModifier = 178,
            StaminaItemDurationModifier = 179,
            ZombieCombustible = 180,
            ZombieKnockdownVulnerability = 181,
            FatigueRateModifier = 182,
            StaminaDrainModifier = 183,
            PlagueNodeToxicPresence = 184,
            PlagueNodeVariant = 185,
            PlagueNodeDamageVulnerability_Explosion = 186,
            PlagueNodeDamageVulnerability_Fire = 187,
            PlagueNodeDamageVulnerability_Melee = 188,
            PlagueNodeDamageVulnerability_Ranged = 189,
            PlagueNodeCreeping = 190,
            PlagueNodeDamageThresholds = 191,
            ZombieKillReward = 192,
            PlagueNodeMiasma = 193,
            ZombieClumsy = 194,
            Count = 195,
            ECharacterStatType_MAX = 196
        }
        public enum ECommunityResourceType : byte
        {
            Ammo = 0,
            Food = 1,
            Fuel = 2,
            Influence = 3,
            Materials = 4,
            Meds = 5,
            Parts = 6,
            Prestige = 7,
            Counts = 8,
            ECommunityResourceType_MAX = 9
        }
        public enum EGamePlayMode
        {
            Vanilla = 0,
            Daybreak = 1,
            Heartland = 2,
            Chariot = 3,
            Num = 4,
            EGamePlayMode_MAX = 5
        }
        public enum EEnclaveType : byte
        {
            Default = 0,
            AmbientMission = 1,
            Legacy = 2,
            RadioTrader = 3,
            Persistent = 4,
            Num = 5,
            EEnclaveType_MAX = 6
        }
        public enum EEquipmentSlot
        {
            Melee = 0,
            Ranged = 1,
            Rucksack = 2,
            CloseCombat = 3,
            Backpack = 4,
            Sidearm = 5,
            Temporary = 6,
            Count = 7,
            EEquipmentSlot_MAX = 8
        }
        public enum EFacilityState
        {
            Destroyed = 0,
            Building = 1,
            Completed = 2,
            Damaged = 3,
            Infested = 4,
            Count = 5,
            EFacilityState_MAX = 6
        }
        public enum EMeleeTypeEnum : byte
        {
            Blunt = 0,
            Bladed = 1,
            Heavy = 2,
            EMeleeTypeEnum_MAX = 3
        }
        public enum EMiscellaneousItemSubType
        {
            None = 0,
            Luxury = 1,
            Note = 2,
            VehicleRepair = 3,
            VehicleRefuel = 4,
            EMiscellaneousItemSubType_MAX = 5
        }
        public enum EMiscellaneousItemType
        {
            AMMO = 0,
            BACKPACK = 1,
            CLOSE_COMBAT_WEAPON = 2,
            CONSUMABLE = 3,
            CRAFTING = 4,
            FACILITY_MOD = 5,
            MELEE_WEAPON = 6,
            MISCELLANEOUS = 7,
            RANGED_WEAPON = 8,
            RANGED_WEAPON_MOD = 9,
            RESOURCE = 10,
            RUCKSACK = 11,
            EMiscellaneousItemType_MAX = 12
        }
        enum EStandingSimulationRewardType
        {
            DeliverRucksack = 0,
            SecureSite = 1,
            DestroyInfestation = 2,
            DestroyHorde = 3,
            KillJuggernaut = 4,
            KillFeral = 5,
            KillBloater = 6,
            KillScreamer = 7,
            KillOrRouteHostileHuman = 8,
            DestroyHostileHumanEnclave = 9,
            KillXZombies = 10,
            ClaimOutpost = 11,
            CuringBloodPlague = 12,
            KillPlagueHeart = 13,
            KillBloodPlagueJuggernaut = 14,
            AddCommunityMember = 15,
            BoonsBanesKillRewards = 16,
            BoonsBanesKillCesspitZombie = 17,
            Count = 18,
            EStandingSimulationRewardType_MAX = 19
        };
        public enum ETimeOfDayPeriod : byte
        {
            Daytime = 0,
            Nighttime = 1,
            ETimeOfDayPeriod_MAX = 2
        }
        public enum EZombieType : byte
        {
            None = 0,
            SlowZombie = 1,
            FastZombie = 2,
            Bloater = 3,
            HumanTurnedZombie = 4,
            Crawler = 5,
            Screamer = 6,
            Feral = 7,
            Juggernaut = 8,
            Count = 9,
            EZombieType_MAX = 10
        }
    }
}
